
import './globals.css'
import { Inter } from 'next/font/google'
import { Theme, Box} from '@radix-ui/themes';
import {NavBar} from './NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>

          <Theme accentColor="bronze" grayColor="sand" radius="large" scaling="95%" style={{height: '100%'}}>
          
            <Box width="100%" height="100%">
                {/* <NavBar
                 city={city}
                 setCity={setCity}
                 dataset={dataset}
                 setDataset={setDataset}
                /> */}
                {children}
            </Box>

          </Theme>
          
        </body>
    </html>
  )
}
